# Generated by Django 3.0.4 on 2020-04-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('episode', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('created', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('air_date', models.CharField(max_length=200)),
                ('episode', models.CharField(max_length=200)),
                ('characters', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('created', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('dimension', models.CharField(max_length=200)),
                ('residents', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('created', models.CharField(max_length=200)),
            ],
        ),
    ]
